### PR TITLE
package.json entries added for gulp tasks

### PR DESCRIPTION
**Pull request by enricolucia**
Hi!
Nice UI/UX first of all.
I've added package.json for gulp tasks and jshinting.

### CODE REVIEW

**Comment by ramonvictor** [comment]
Hi @enricolucia! Thanks for your feedback and PR as well.
Sorry for my delay to respond, I will test your changes and get back to you as soon as possible.

**Comment by enricolucia** [comment]
Welcome!
Whenever you have time 👍

**Comment by ramonvictor** [comment]
@enricolucia sorry for taking so long. PR merged! :)

**Comment by enricolucia** [comment]
@ramonvictor  no worries man, thanks :)

**Pull request merged**
